# Site
repository: AwangPraja01/AwangPraja01.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Awang Praja Anugerah
title: Front-End Developer
email: awangpa9@gmail.com
website: https://awangpraja01.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: AwangPraja01
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: awangpa1020
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: Enjoy the Code
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Enjoy the Code Youtube Channel
#   icon: fab fa-youtube
#   url: https://www.youtube.com/channel/UCK_o0svUHaJkoWKwwICBVzg
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, nama saya Awang Praja Anugerah dan saya seorang front - end developher. Selain berperan sebagai front - end developher saya juga dapat berperan sebagai back - end developher. Saya telah membuat berbagai project yang dapat anda lihat pada github saya.

  Framework yang saya kuasai diataranya <mark>React</mark> <mark>Next JS</mark> <mark>Express JS</mark> <mark>Laravel</mark> <mark>Git</mark>

  Bahasa pemograman yang saya kuasai  diataranya <mark>Javascript</mark> <mark>HTML & CSS</mark> <mark>PHP</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: COVID 19 Tracker
        link: github.com/AwangPraja01/covid_tracker_with_nextjs_and_typescript
        # link_text: Project Website
        additional_links:
          - title: github.com/AwangPraja01
            icon: fab fa-github
            url: github.com/AwangPraja01
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Project COVID 19 Tracker merupakan salah satu project terbaik yang pernah saya buat.
        description: | # this will include new lines to allow paragraphs
          Saya membuat proyek ini sebagai cara untuk mempelajari <mark>Next js</mark> dan <mark>Typescript</mark>. Saya telah mempelajari banyak keterampilan melalui ini dan saya sangat bangga memiliki ini dalam portofolio saya.
      - layout: top-middle
        title: Showcase Website
        link: github.com/AwangPraja01/showcase_website
        # link_text: Project Website
        additional_links:
          - title: github.com/AwangPraja01
            icon: fab fa-github
            url: github.com/AwangPraja01
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Project Showcase Website merupakan project pertama saya yang menerapkan full stack pada pembuatannya
        description: | # this will include new lines to allow paragraphs
          Project Showcase Website ini saya buat untuk belajar menjadi full stack developher. Project ini saya buat dengan <mark>React</mark> sebagai tampilan antar mukanya atau front - end sedangkan untuk storage dan back - endnya saya menggunakan <mark>Express JS</mark> dan <mark>Firebase</mark>. Saya sangat bangga karena saya bisa membuat project full stack pertama saya.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SMKN TI Pontianak
        caption: 2018 - 2021
        sub_title: Analisis Pengujian Laboratorium
        quote: >
          SMK SMTI Pontianak yang dulunya adalah STMA didirikan pada tanggal 15 Januari 1968 yang dikukuhkan dengan SK Gubernur KDH Tk.1 Kalimantan Barat No. 01/11-E/68. Pengelolaan SMTI Pontianak diserah terimakan dari Pemda Tk. 1 Kalimantan Barat ke Pihak Departemen Perindustrian.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
